# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "D:/software/Program/source/projects/nfc/libnfc-build/source;D:/software/Program/source/projects/nfc/libnfc-build/build-src")
set(CPACK_CMAKE_GENERATOR "Visual Studio 17 2022")
set(CPACK_COMPONENTS_ALL "Unspecified;examples;headers;libraries;utils")
set(CPACK_COMPONENT_EXAMPLES_DEPENDS "libraries")
set(CPACK_COMPONENT_EXAMPLES_DISPLAY_NAME "Example Applications")
set(CPACK_COMPONENT_HEADERS_DEPENDS "libraries")
set(CPACK_COMPONENT_HEADERS_DISABLED "TRUE")
set(CPACK_COMPONENT_HEADERS_DISPLAY_NAME "Development Headers")
set(CPACK_COMPONENT_LIBRARIES_DISPLAY_NAME "NFC Library")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "D:/software/CMake/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "libnfc built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "ZIP")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "D:/software/Program/source/projects/nfc/libnfc-build/build-src;libnfc;ALL;/")
set(CPACK_INSTALL_PREFIX "C:/Program Files/libnfc")
set(CPACK_MODULE_PATH "D:/software/Program/source/projects/nfc/libnfc-build/source/cmake/modules/")
set(CPACK_NSIS_DISPLAY_NAME "libnfc")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "libnfc")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "D:/software/Program/source/projects/nfc/libnfc-build/build-src/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "Roel Verdult <roel@libnfc.org>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "D:/software/Program/source/projects/nfc/libnfc-build/source/README-Windows.md")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Near Field Communication (NFC) library")
set(CPACK_PACKAGE_FILE_NAME "libnfc-1.8.0-win64")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "libnfc")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "libnfc")
set(CPACK_PACKAGE_NAME "libnfc")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Roel Verdult")
set(CPACK_PACKAGE_VERSION "1.8.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "8")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "D:/software/Program/source/projects/nfc/libnfc-build/source/COPYING")
set(CPACK_RESOURCE_FILE_README "D:/software/CMake/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "D:/software/CMake/share/cmake-3.28/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "ZIP")
set(CPACK_SOURCE_IGNORE_FILES "~$;/\\.git/;bin/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "D:/software/Program/source/projects/nfc/libnfc-build/build-src/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "libnfc-1.8.0")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "D:/software/Program/source/projects/nfc/libnfc-build/build-src/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
